# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='is_closed',
            field=models.TimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='is_open',
            field=models.TimeField(db_index=True),
        ),
    ]
